# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b42de7e061ac19e9872cd57bafb2a11dbe415bafb9bce07e43b86dc30b5601f921da770c249a79349c41177ad29cf67e4d8262acbfdb1126bf5e03732510fcb5

test:
  secret_key_base: 73ec61912fa33133c64c8a927dacd46b3662e6d5a19054181ce1b8dc4789688fb90fc6015141b749d89aadacb0e3d97087d309c83cae5cd171c853457f7d248f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
